In [1]:
import numpy as np

In [2]:
A = np.array([
    [2,4,5,6,7],
    [4,5,12,4,5],
    [23,56,4,6,15],
    [12,15,19,20,4],
    [9,8,12,11,50]
])

A_t = A.T

B = A + A_t

print(B)

[[  4   8  28  18  16]
 [  8  10  68  19  13]
 [ 28  68   8  25  27]
 [ 18  19  25  40  15]
 [ 16  13  27  15 100]]


In [4]:
A = np.array([
    [-1, 1],
    [-2, 1],
    [3, 1]
])

B = np.array([[4], [5], [6]])

variables = np.linalg.pinv(A).dot(B)
variables

array([[0.28571429],
       [5.        ]])

In [6]:
mat = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

np.linalg.pinv(mat)

array([[-1.33333333, -0.33333333,  0.66666667],
       [ 1.08333333,  0.33333333, -0.41666667]])

In [7]:
A = [[3, 4], [3, 2]]

np.linalg.eig(A)

(array([ 6., -1.]),
 array([[ 0.8       , -0.70710678],
        [ 0.6       ,  0.70710678]]))