# Concatenation

In [24]:
import pandas as pd
import numpy as np

pd.options.display.float_format = '{:.2f}'.format

## Concatenating Series

In [9]:
x1 = np.random.rand(2, 5) * 100
x1

array([[ 9.22599929, 39.06146887, 15.00728471, 42.07836517, 46.39776163],
       [43.78742039, 35.0697646 , 92.09783325, 49.05788076, 89.8226577 ]])

In [10]:
x2 = np.random.rand(2, 5) * -1
x2

array([[-0.59621537, -0.96060429, -0.34259759, -0.93040064, -0.55501682],
       [-0.20084435, -0.36979458, -0.55091497, -0.87423104, -0.84265797]])

In [12]:
np.concatenate([x1, x2]).shape

(4, 5)

In [14]:
np.concatenate([x1, x2], axis=1)

array([[ 9.22599929, 39.06146887, 15.00728471, 42.07836517, 46.39776163,
        -0.59621537, -0.96060429, -0.34259759, -0.93040064, -0.55501682],
       [43.78742039, 35.0697646 , 92.09783325, 49.05788076, 89.8226577 ,
        -0.20084435, -0.36979458, -0.55091497, -0.87423104, -0.84265797]])

In [17]:
s1 = pd.Series(x1[0], index=['a', 'b', 'c', 'd', 'e'])
s1

a    9.23
b   39.06
c   15.01
d   42.08
e   46.40
dtype: float64

In [18]:
s2 = pd.Series(x2[0], ['c', 'd', 'e', 'f', 'g'])
s2

c   -0.60
d   -0.96
e   -0.34
f   -0.93
g   -0.56
dtype: float64

In [21]:
pd.concat([s1,s2], axis=1)

0     1
a  9.23   NaN
b 39.06   NaN
c 15.01 -0.60
d 42.08 -0.96
e 46.40 -0.34
f   NaN -0.93
g   NaN -0.56

In [23]:
pd.concat([s1.reset_index(drop=True), s2.reset_index(drop=True)], axis=1)

0     1
0  9.23 -0.60
1 39.06 -0.96
2 15.01 -0.34
3 42.08 -0.93
4 46.40 -0.56

## Concatenating Dataframes

In [26]:
df1 = pd.DataFrame(np.random.rand(3,2)*10, columns=['a', 'b'])
df2 = pd.DataFrame(np.random.rand(3,2)*-1, columns=['a', 'b'], index=[2,3,4])

In [28]:
pd.concat([df1, df2])

a     b
0  5.35  7.24
1  0.57  7.36
2  2.16  4.03
2 -0.82 -0.68
3 -0.89 -0.86
4 -0.07 -0.94

In [31]:
pd.concat([df1, df2], axis=1, join='inner')

a    b     a     b
2 2.16 4.03 -0.82 -0.68

In [33]:
df1.append(df2)

a     b
0  5.35  7.24
1  0.57  7.36
2  2.16  4.03
2 -0.82 -0.68
3 -0.89 -0.86
4 -0.07 -0.94

In [35]:
df1.T.append(df2.T).T

a    b     a     b
0 5.35 7.24   NaN   NaN
1 0.57 7.36   NaN   NaN
2 2.16 4.03 -0.82 -0.68
3  NaN  NaN -0.89 -0.86
4  NaN  NaN -0.07 -0.94