In [19]:
import torch
from torchvision import datasets

## Tensores

In [2]:
A = torch.randn((8, 3, 5))

In [3]:
A.size()

torch.Size([8, 3, 5])

In [4]:
A[0][0]

tensor([-0.8127,  1.1621, -0.3881, -0.4838, -1.1106])

In [5]:
A[0,0]

tensor([-0.8127,  1.1621, -0.3881, -0.4838, -1.1106])

In [6]:
A[0, :, 2]

tensor([-0.3881, -0.8107,  2.6452])

In [7]:
z = torch.zeros((5, 5))

In [8]:
z.dtype

torch.float32

In [9]:
d = torch.randint(2, (5, 5))
d

tensor([[0, 1, 1, 0, 0],
        [1, 1, 1, 1, 0],
        [0, 0, 0, 1, 1],
        [0, 0, 1, 1, 1],
        [1, 1, 0, 1, 1]])

In [10]:
d.dtype

torch.int64

In [11]:
z + d

tensor([[0., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [0., 0., 0., 1., 1.],
        [0., 0., 1., 1., 1.],
        [1., 1., 0., 1., 1.]])

In [12]:
z.device

device(type='cpu')

In [13]:
torch.backends.mps.is_available()

True

In [14]:
DEVICE = torch.device('mps' if torch.backends.mps.is_available() else 'cpu')

In [15]:
x = torch.randn((3, 5))
y = torch.ones_like(x, device=DEVICE)

In [16]:
x.to(DEVICE)
print(x)

tensor([[-1.0162, -0.0567,  0.6827,  0.6893,  0.6106],
        [ 0.0801, -0.6292, -0.4832, -2.0192,  0.8918],
        [ 0.5481, -0.9306, -0.6189, -0.0730,  0.0867]])


In [18]:
print(y)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], device='mps:0')


In [20]:
dir(datasets)

['CIFAR10',
 'CIFAR100',
 'CLEVRClassification',
 'Caltech101',
 'Caltech256',
 'CelebA',
 'Cityscapes',
 'CocoCaptions',
 'CocoDetection',
 'Country211',
 'DTD',
 'DatasetFolder',
 'EMNIST',
 'EuroSAT',
 'FER2013',
 'FGVCAircraft',
 'FakeData',
 'FashionMNIST',
 'Flickr30k',
 'Flickr8k',
 'Flowers102',
 'FlyingChairs',
 'FlyingThings3D',
 'Food101',
 'GTSRB',
 'HD1K',
 'HMDB51',
 'INaturalist',
 'ImageFolder',
 'ImageNet',
 'KMNIST',
 'Kinetics',
 'Kinetics400',
 'Kitti',
 'KittiFlow',
 'LFWPairs',
 'LFWPeople',
 'LSUN',
 'LSUNClass',
 'MNIST',
 'Omniglot',
 'OxfordIIITPet',
 'PCAM',
 'PhotoTour',
 'Places365',
 'QMNIST',
 'RenderedSST2',
 'SBDataset',
 'SBU',
 'SEMEION',
 'STL10',
 'SUN397',
 'SVHN',
 'Sintel',
 'StanfordCars',
 'UCF101',
 'USPS',
 'VOCDetection',
 'VOCSegmentation',
 'VisionDataset',
 'WIDERFace',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_optical_flow',
 'caltech',
 '

In [22]:
cifar = datasets.CIFAR10('../Datasets/CIFAR10', download=True)

100.0%


Extracting ../Datasets/CIFAR10/cifar-10-python.tar.gz to ../Datasets/CIFAR10


In [24]:
cifar_tensor = torch.Tensor(cifar.data)

In [26]:
cifar_tensor.size()

torch.Size([50000, 32, 32, 3])