In [2]:
import torch
import numpy as np

In [3]:
torch.__version__

'2.0.1'

In [4]:
scalar = torch.randn(1)
vector = torch.zeros(1, 10)
matrix = torch.ones(2, 2)

print(scalar)
print(vector)
print(matrix)

tensor([0.4074])
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [5]:
t5 = torch.randn(5, 2, 3)
t5

tensor([[[ 0.2552, -1.2688,  2.3064],
         [ 0.8424, -1.0146, -0.0908]],

        [[-0.9358,  1.3423,  0.6172],
         [-0.8968,  0.1386, -0.1440]],

        [[-0.6217, -1.3064,  0.3971],
         [ 0.4237, -2.4088,  0.7781]],

        [[-0.5077, -1.3070, -0.1086],
         [ 0.3377,  0.1095,  0.8345]],

        [[ 1.2855, -0.7359, -0.2990],
         [-0.1921, -1.9423,  0.0746]]])

In [6]:
torch.tensor([[2, 2], [3, 7 ]])

tensor([[2, 2],
        [3, 7]])

In [7]:
matrix.shape

torch.Size([2, 2])

In [8]:
t5.shape

torch.Size([5, 2, 3])

In [9]:
matrix.ndim

2

In [10]:
t5.ndim

3

In [11]:
matrix.dtype

torch.float32

In [12]:
matrix_f32 = torch.tensor([[3.1, 3.2], [3.3, 3.4]])
matrix_uint64 = torch.tensor([[3, 3], [4, 4]])

for vector in [matrix_f32, matrix_uint64]:
    print(f"Vector shape: {vector.shape} type: {vector.dtype}")

Vector shape: torch.Size([2, 2]) type: torch.float32
Vector shape: torch.Size([2, 2]) type: torch.int64


In [13]:
(matrix_f32 + matrix_uint64).dtype

torch.float32

In [14]:
matrix_uint64.to(torch.float32)

tensor([[3., 3.],
        [4., 4.]])

In [15]:
matrix_uint64.device

device(type='cpu')

In [16]:
if torch.has_mps:
    matrix_uint64_mps = matrix_uint64.to("mps")
    print(matrix_uint64_mps, matrix_uint64_mps.dtype)
    print(matrix_uint64_mps.device)

tensor([[3, 3],
        [4, 4]], device='mps:0') torch.int64
mps:0


## Working with Numpy

In [17]:
type(matrix.numpy())

numpy.ndarray

In [18]:
np_vector = np.ones(5)
np_vector

array([1., 1., 1., 1., 1.])

In [20]:
torch.from_numpy(np_vector).dtype

torch.float64

## Operations with Tensors

In [21]:
zeros_tensor = torch.zeros((3, 4))
ones_tensor = torch.ones((3, 4))
random_tensor = torch.randn((4))

In [22]:
added_tensor = zeros_tensor + ones_tensor
subtracted_tensor = zeros_tensor - ones_tensor
divided_tensor = random_tensor / ones_tensor

In [23]:
divided_tensor

tensor([[-0.5789, -1.7996,  1.0553, -0.4069],
        [-0.5789, -1.7996,  1.0553, -0.4069],
        [-0.5789, -1.7996,  1.0553, -0.4069]])

## Matrices operations

In [24]:
matrix_1 = torch.randn(2, 3)
matrix_2 = torch.randn(3, 2)

torch.matmul(matrix_1, matrix_2)

tensor([[ 0.0636,  0.2255],
        [-0.1491, -0.7290]])