In [1]:
import numpy as np

In [2]:
vector = np.array([1/2,1/2,1/2,1/2])


In [3]:
norma = np.linalg.norm(vector)
print(norma)

1.0


In [4]:
mar = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(mar.T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [7]:
7*(0) + 2 - (2)

0

In [8]:
3*(0) + 5 - (2)

3

In [10]:
def evaluate(x, y):
    val_1 = 7*x - y 
    val_2 = 3*x - y
    
    print(val_1 == -2)
    print(val_2 == -5)

In [14]:
x = 3/4
y = 7+1/4

evaluate(x,y)

True
True
